name: Continuous Integration

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update -q
        && sudo apt-get install clang-format-20 -q -y

    - uses: actions/setup-python@v5
      with: { python-version: "3.12" }

    - name: Install codespell
      run: pip3 install codespell

    - name: Lint
      run: cmake -D FORMAT_COMMAND=clang-format-20 -P cmake/lint.cmake

    - name: Spell check
      if: always()
      run: cmake -P cmake/spell.cmake

  coverage:
    needs: [lint]

    runs-on: ubuntu-latest
    container: rootproject/root:latest

    # To enable coverage, delete the last line from the conditional below and
    # edit the "<name>" placeholder to your GitHub name.
    # If you do not wish to use codecov, then simply delete this job from the
    # workflow.
    if: github.repository_owner == 'rlalik'
      # && false

    steps:
    - uses: actions/checkout@v4

    - name: Install LCov
      run: apt-get update -q
        && apt-get install lcov -q -y

    - name: Configure
      run: cmake --preset=ci-coverage

    - name: Build
      run: cmake --build build/coverage -j 2

    - name: Test
      working-directory: build/coverage
      run: ctest --output-on-failure --no-tests=error -j 2

    - name: Process coverage info
      run: cmake --build build/coverage -t coverage

    - name: Submit to Coveralls.io
      uses: coverallsapp/github-action@v2

  sanitize:
    needs: [lint]

    runs-on: rootproject/root:latest

    env: { CXX: clang++-21 }

    steps:
    - uses: actions/checkout@v4

    - name: Install Clang
      run: apt-get update -q
        && apt-get install clang-21 libomp-21-dev libclang-rt-21-dev -q -y

    - name: Configure
      run: cmake --preset=ci-sanitize

    - name: Build
      run: cmake --build build/sanitize -j 2

    - name: Test
      working-directory: build/sanitize
      env:
        ASAN_OPTIONS: "strict_string_checks=1:\
          detect_stack_use_after_return=1:\
          check_initialization_order=1:\
          strict_init_order=1:\
          detect_leaks=1:\
          halt_on_error=1"
        UBSAN_OPTIONS: "print_stacktrace=1:\
          halt_on_error=1"
      run: ctest --output-on-failure --no-tests=error -j 2

  test:
    needs: [lint]

    strategy:
      matrix:
        include:
          - os: ubuntu-25.10
            container: rootproject/root:6.38.00-ubuntu25.10
          - os: ubuntu-25.04
            container: rootproject/root:6.36.00-ubuntu25.04
          - os: ubuntu-24.10
            container: rootproject/root:6.34.00-ubuntu24.10
          - os: ubuntu-24.04
            container: rootproject/root:6.34.00-ubuntu24.04
          - os: ubuntu-24.04
            container: rootproject/root:6.32.04-ubuntu24.04

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
    - uses: actions/checkout@v4

    - name: Install static analyzers for Ubuntu 25.10
      if: matrix.os == 'ubuntu-25.10'
      run: >-
        apt-get install clang-tidy-21 cppcheck -y -q

        update-alternatives --install
        /usr/bin/clang-tidy clang-tidy
        /usr/bin/clang-tidy-21 210

    - name: Install static analyzers for Ubuntu 25.04
      if: matrix.os == 'ubuntu-25.04'
      run: >-
        apt-get install clang-tidy-20 cppcheck -y -q

        update-alternatives --install
        /usr/bin/clang-tidy clang-tidy
        /usr/bin/clang-tidy-20 200

    - name: Install static analyzers for Ubuntu 24.10
      if: matrix.os == 'ubuntu-24.10'
      run: >-
        apt-get install clang-tidy-20 cppcheck -y -q

        update-alternatives --install
        /usr/bin/clang-tidy clang-tidy
        /usr/bin/clang-tidy-20 200

    - name: Install static analyzers for Ubuntu 24.04
      if: matrix.os == 'ubuntu-24.04'
      run: >-
        apt-get update

        apt-get install clang-tidy-20 cppcheck -y -q

        update-alternatives --install
        /usr/bin/clang-tidy clang-tidy
        /usr/bin/clang-tidy-20 200

    - name: Configure
      if: startsWith(matrix.os, 'ubuntu-')
      run: cmake --preset=ci-ubuntu

    - name: Build
      run: cmake --build build --config Release -j 2

    - name: Install
      run: cmake --install build --config Release --prefix prefix

    - name: Test
      working-directory: build
      run: ctest --output-on-failure --no-tests=error -C Release -j 2

  docs:
    # Deploy docs only when builds succeed
    needs: [sanitize, test]

    runs-on: rootproject/root:latest

    # To enable, first you have to create an orphaned gh-pages branch:
    #
    #    git switch --orphan gh-pages
    #    git commit --allow-empty -m "Initial commit"
    #    git push -u origin gh-pages
    #
    # Edit the <name> placeholder below to your GitHub name, so this action
    # runs only in your repository and no one else's fork. After these, delete
    # this comment and the last line in the conditional below.
    # If you do not wish to use GitHub Pages for deploying documentation, then
    # simply delete this job similarly to the coverage one.
    if: github.ref == 'refs/heads/master'
      && github.event_name == 'push'
      && github.repository_owner == '<name>'
      && false

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with: { python-version: "3.14" }

    - name: Install m.css dependencies
      run: pip3 install jinja2 Pygments

    - name: Install Doxygen
      run: sudo apt-get update -q
        && sudo apt-get install doxygen -q -y

    - name: Build docs
      run: cmake "-DPROJECT_SOURCE_DIR=$PWD" "-DPROJECT_BINARY_DIR=$PWD/build"
        -P cmake/docs-ci.cmake

    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/docs/html
